### ISSUE TITLE
ReactFiberReconciler not included with rect-dom > v16.0.0-alpha.6

### ISSUE THREAD

**Issue by drom** [sidorares/react-x11#6]
Looks like your package require:
```json
"react": "^16.0.0-alpha.5",
"react-dom": "^16.0.0-alpha.5",
```
react-dom 16.0.0-alpha.7 ... 12 don't include ReactFiberReconciler anymore.

### Short term:

You should probably remove "^" from package.json

### Long term:

We ween a way to get latest ReactFiberReconciler code. Somehow.

**Comment by sidorares** [comment]
> react-dom 16.0.0-alpha.7 ... 12 don't include ReactFiberReconciler anymore.

do you know where did it go? is it in separate package now?

yes, I'm 👍 for locking versions for now

**Comment by sidorares** [comment]
did you have any luck running it with alpha.5 ? ( not sure how good is the current state, obviously it's far from prod ready but can't remember if it works out of the box at all ). Will try to test over weekend

**Comment by drom** [comment]
Yes, your code runs with alpha.6.
I am doing custom renderer and taking your code as example. I am using alpha.6 that is last shipped with Reconciler. I haven't found Reconciler alpha-7..12 in any other NPM package from React team directly :disappointed:

**Comment by drom** [comment]
@sidorares under linux (OpenSuSe Tumbleweed) I see the window, with messy content, that is just previous screenshot. I can resize, but content is not redrawn.

**Comment by drom** [comment]
Found some info here: https://github.com/facebook/react/issues/9103
