### ISSUE TITLE
Guide on how to start experimenting with the library

### ISSUE THREAD

**Issue by AleksanderKoko** [sidorares/react-x11#8]
Hi, guys. Congrats on this project, an interesting one. However, I had problems getting it running. 

I tried to babel a file (turn on something Node can execute), but no success. Did `node simple.js` after turned to normal JS, but no luck. It might be only my case because I'm not tech savvy on Node in general.

**Comment by phil-r** [comment]
Hello @AleksanderKoko I've also wanted to play with this lib, and that how I've managed to make it work:
- go to the root of the project and run `npm i` to install dependencies
- run `node examples/simple-nojsx` to launch example that's not using jsx

to run other examples you'll need `babel-node` which is no longer a part of `babel`, but a part of `babel-cli`... or you can clone my fork and follow [this instructions
](https://github.com/phil-r/react-x11#trying-it-out)


Anyway I wasn't able to achieve the same result as on gif in Readme

**Comment by sidorares** [comment]
@phil-r feel free so send pr with updated documentation, very keen to improve since this library started to get some attention and it's no longer just me

**Comment by sidorares** [comment]
oops I see you already did

**Comment by sidorares** [comment]
@phil-r have you tried running react-devtools? It's standalone electron app, `./node_modules/.bin/react-devtools`. Will add more to readme later today, on mobile now

**Comment by phil-r** [comment]
@sidorares no, I haven't figured out how to use them, will try later ;)

**Comment by sidorares** [comment]
just starting https://npmjs.org/package/react-devtools should be enough, no additional configuration required

**Comment by AleksanderKoko** [comment]
Hey @phil-r and @sidorares . Thanks for the fast response. Tried again and it looks I did something similar on my last attempt. Again no new window when executing the commands (here also on docs) seems to pop up.

Here's one screenshot on my case. Am I missing something, or is not working only for me?

<img width="1408" alt="screen shot 2017-06-12 at 09 32 18" src="https://user-images.githubusercontent.com/3903072/27023321-582d9bae-4f52-11e7-97d6-43582560e4a1.png">

**Comment by AleksanderKoko** [comment]
If this tool helps to build products less memory/cpu intensive than Electron, I really would like to help :D

**Comment by sidorares** [comment]
Internally it's using [node-x11](https://github.com/sidorares/node-x11) to communicate with X Server. You can try first to play with examples from node-x11. Note that osx no longer ships x server by with os, you need to install it manually - https://www.xquartz.org/

> If this tool helps to build products less memory/cpu intensive than Electron

Yes, this is one of the goals, apps like https://getkap.co/ - not extremely complicated UI, should not take hundreds of MBs on disk and in memory (not blaming Kap here - it's a great app)

**Comment by sidorares** [comment]
@AleksanderKoko what happens if you just type `xeyes` or `xterm` command in your terminal?

**Comment by AleksanderKoko** [comment]
Now it works. Didn't know had to install that software. Would play a bit with this project and come back with stuff :)

**Comment by AleksanderKoko** [comment]
I think we can close this issue now @sidorares . From activity monitor, I can see it's not that intensive. Tried React Mac before and it was intensive surprisingly.
